# Generated by Django 4.2.6 on 2024-01-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_alter_userfine_created_by_alter_userfine_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfine',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userfine',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
