# Generated by Django 4.2.6 on 2024-01-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userfine_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mony', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
