# Generated by Django 4.2.6 on 2024-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_finechart_email_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmony',
            name='total_mony',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finechart',
            name='fine_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='fine_amount',
            field=models.IntegerField(),
        ),
    ]
